AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Name:
    Description: The service name
    Type: String
  Image:
    Description: Image name
    Type: String
Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join ["-", [ !Ref Name, !Ref Image ] ]
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
                {
                      "rulePriority": 10,
                      "description": "Keep only the last 5 production tagged image, expire all others",
                      "selection": {
                          "tagStatus": "tagged",
                          "tagPrefixList": [
                            "production"
                          ],
                          "countType": "imageCountMoreThan",
                          "countNumber": 5
                      },
                      "action": {
                          "type": "expire"
                    }
                },
                {
                    "rulePriority": 20,
                    "description": "Image count more than 10",
                    "selection": {
                        "tagStatus": "any",
                        "countType": "imageCountMoreThan",
                        "countNumber": 10
                    },
                    "action": {
                        "type": "expire"
                    }
                }
            ]
          }
Outputs:
  ecrrepo:
    Value: !Ref ECRRepository
  EcrURL:
    Description: ECR url.
    Value: !Sub https://console.aws.amazon.com/ecs/home?region=${AWS::Region}#/repositories/${ECRRepository}#images;tagStatus=ALL
