AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketName:
    Description: Prefix of the S3 bucket
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  S3BucketName:
    Description: "Bucket Name/ARN"
    Value: !Ref S3Bucket
